# Generated by Django 5.2.6 on 2025-09-17 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_name', models.CharField(default='', max_length=200)),
                ('bus_start', models.CharField(default='', max_length=200)),
                ('destination', models.CharField(default='', max_length=200)),
                ('seats', models.IntegerField(default=1)),
                ('available_seats', models.IntegerField()),
                ('departure_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_name', models.CharField(max_length=50)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketsystem.bus')),
            ],
        ),
    ]
