# Generated by Django 5.2.4 on 2025-09-19 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsystem', '0002_booking_seats_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
