# Generated by Django 5.2.4 on 2025-09-19 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsystem', '0003_bus_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='bus_number',
            field=models.CharField(default=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='bus',
            name='bus_name',
            field=models.CharField(default='', max_length=55),
        ),
        migrations.AlterField(
            model_name='bus',
            name='bus_start',
            field=models.CharField(default='', max_length=55),
        ),
        migrations.AlterField(
            model_name='bus',
            name='destination',
            field=models.CharField(default='', max_length=55),
        ),
    ]
