# Generated by Django 5.2.4 on 2025-09-19 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsystem', '0004_bus_bus_number_alter_bus_bus_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='bus_number',
            field=models.CharField(default='', max_length=50),
        ),
    ]
